springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /api-docs
    filter: false
    operations-sorter: method
spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  datasource:
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      leak-detection-threshold: 30000 # 30 seconds
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

