# 강제 마이그레이션 실행을 위한 설정
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
  
  # Flyway 마이그레이션 강제 실행 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    fail-on-missing-locations: false
    # 마이그레이션 강제 확인
    validate-on-migrate: true

# 로깅 레벨 향상 (디버깅용)
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.web: DEBUG
    com.gk.happytteokordersystem: DEBUG