springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /api-docs
    filter: false
    operations-sorter: method
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
