name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: happy-tteok
        
    - name: Configure Docker
      run: gcloud auth configure-docker
      
    - name: Build and deploy to Cloud Run
      run: |
        gcloud run deploy happytteok-order-system \
          --source . \
          --platform managed \
          --region asia-northeast3 \
          --allow-unauthenticated
